name: Daily Backup Job Inner
on:
  schedule: 
    - cron: '25 11 * * 1-5'
  repository_dispatch:
    types: schedule

jobs:
  run-this:
    runs-on: ubuntu-latest
    steps:
    - name: Get text value from payload
      run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo "Action url is ${{ env.ACTION_URL }}"
          echo "Event Payload"
          echo "${{ github.event.client_payload.text }} "
          pwd
          ls
          
