name: Deployment
on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      test:
        description: "Test run the deployment without actually deploying it. Type: test"
        required: false

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_I: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - name: deploy
        run: |
          set -exv
          aws s3 ls

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: deploy
        run: |
          set -exv
          npm install broken-link-checker -g

          blc https://waitlist.qalort.com -ro
