name: If Condition

on:
  push:
    branches:
      - if-condition
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#     - name: Checkout code
#       uses: actions/checkout@master
    
    - name: This should fail
      uses: actions/upload-artifact@v1
      with:
        name: envvar
        path: variables.txt
    - name: failure 
      if: failure()
      run: |
        echo "its a failure"
    - name: success 
      if: success()
      run: |
        echo "its a success"
        
    - name: This should pass
      if: always()
      run: |
       echo "This passed"
    - name: failure 2
      if: failure()
      run: |
        echo "its a failure"
    - name: success 2 
      if: success()
      run: |
        echo "its a success"
  
  fail:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          echo "its a failure"
          
  success:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: |
          echo "its a success"
