name: If Condition

on:
  push:
    branches:
      - if-condition
jobs:
  one:
    if: "github.event.push.repository.fork"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout code
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        export GITHUB_TAG=rc-$(git tag -l --sort=committerdate |tail -1 | cut -f2 -d"-")-$(git rev-parse HEAD | cut -c 1-7)
        echo $GITHUB_TAG
        echo "::set-env name=GITHUB_TAG::$GITHUB_TAG"
        
    - name: get it
      run: |
        echo "this is it ${{ env.GITHUB_TAG}} or this ${GITHUB_TAG} tabi this $GITHUB_TAG"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        export GITHUB_TAG=rc-$(git tag -l --sort=committerdate |tail -1 | cut -f2 -d"-")-$(git rev-parse HEAD | cut -c 1-7)
        echo $GITHUB_TAG
    
    - name: This should fail
      uses: actions/upload-artifact@v1
      with:
        name: envvar
        path: variables.txt
    - name: failure 
      if: failure()
      run: |
        echo "its a failure"
    - name: success 
      if: success() 
      run: |
        echo "its a success"
        
    - name: This should pass
      if: always()
      run: |
       echo "This passed"
    - name: failure 2
      if: failure()
      run: |
        echo "its a failure"
    - name: success 2 
      if: success()
      run: |
        echo "its a success"
  
  fail:
    if: failure()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: fail
        run: |
          echo "its a failure"
          
  success:
    if: success()
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: success
        run: |
          echo "its a success"
          
  out:
    runs-on: ubuntu-latest
    needs: [fail]
    steps:
      - name: success
        run: |
          echo "its a out"
        
  last:
    runs-on: ubuntu-latest
    needs: [out]
    steps:
      - name: success
        run: |
          echo "its a success"
