name: Inspect Contexts

on: [push, pull_request]

env:
  ACTION_URL: "https://github.com/${{ toJson(github.repository) }}/commit/${{ toJson(github.sha) }}/checks"
  ACTION_U: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: sunny
        run: echo "sunny"
        continue-on-error: true
      - name: Inspect contexts
        continue-on-error: true
        run: |
          echo ${{ job.steps.sunny.status }}
          echo ${{ steps.sunny.status }}
          echo "${{ toJson(steps.sunny) }}"
          echo ${{ steps.sunny.outcome }}
          
      - id: nixit
        run: ./${{env.TWAT}}
        continue-on-error: true
        
      - name: Sunny status
        continue-on-error: true
        run: |
          echo "${{ toJson(steps.sunny.outcome) }} and Nixit is ${{ toJson(steps.nixit.outcome) }}"
          
      - name: show all changed files
        continue-on-error: true
        run: |
          git show --pretty="" --name-only ${{ github.event.pull_request.head.sha }}
          
      - name: show all another sha
        continue-on-error: true
        run: |
          git show --pretty="" --name-only ${{ github.event.after }}
          
      - uses: actions/github-script@0.9.0
        continue-on-error: true
        with:
          script: |
            require 'sinatra'
            require 'json'

            post '/payload' do
              push = JSON.parse(request.body.read) # parse the JSON

              # gather the data we're looking for
              pusher = push["pusher"]["name"]
              branch = push["ref"]

              # get a list of all the files touched
              files = push["commits"].map do |commit|
                commit['added'] + commit['modified'] + commit['removed']
              end
              files = files.flatten.uniq

              echo "Here are the list of files:"
              echo $files
            end
          
      - name: Inspect contexts
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"
          echo "URL TO ACTION"
          echo "We have this ${{ env.ACTION_URL }} and below"
          echo "and this too ${{ env.ACTION_U }}"
          export URL="https://github.com/iamtito/react-app/commit/$(echo ${{ toJson(github.sha) }})/checks"
          echo "::set-env name=URL::${URL}"
          export event=$(echo ${{ toJson(github.event_name) }})
          echo $URL
          curl -X POST -H 'Content-type: application/json' --data '{"blocks": [{"type": "section","text": {"type": "mrkdwn","text": "Slack payload test"}},{"type": "section","fields": [{"type": "mrkdwn","text": "*Event* \n ${event}"},{"type": "mrkdwn","text": "*Action URL* \n < ${{ env.URL }} |link>"}]}]}'  ${{ secrets.BVITY_SLACK_WEBHOOK }}
          
          curl -s -d "payload={ \"username\":\"RPPrefresh Job\", \"attachments\":[{\"color\":\"#E01E5A\" , \"text\": \"Test $(echo ${{ toJson(github.event_name) }}) Ignore <${URL}|linking> and the main link <${{ env.ACTION_URL }}|Main>\"}]}" ${{ secrets.BVITY_SLACK_WEBHOOK }}
