name: Inspect Contexts

on: [push]

jobs:
  build:
    name: Inspect contexts
    runs-on: ubuntu-latest
    steps:
      - name: Inspect contexts
        run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo ""
          echo "The job context is:"
          echo "${{ toJson(job) }}"
          echo ""
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo ""
          echo "The runner context is:"
          echo "${{ toJson(runner) }}"
          echo ""
          echo "The strategy context is:"
          echo "${{ toJson(strategy) }}"
          echo ""
          echo "The matrix context is:"
          echo "${{ toJson(matrix) }}"
          echo "URL TO ACTION"
          export URL="https://github.com/iamtito/react-app/commit/$(echo ${{ toJson(github.sha) }})/checks"
          echo $URL
          curl -X POST -H 'Content-type: application/json' --data '{"blocks": [{"type": "section","text": {"type": "mrkdwn","text": "Slack payload test"}},{"type": "section","fields": [{"type": "mrkdwn","text": "*Event* \n $(echo ${{ toJson(github.event_name) }})"},{"type": "mrkdwn","text": "*Action URL* \n <https://github.com/iamtito/react-app/commit/$(echo ${{ toJson(github.sha) }})/checks|link>"}]}]}'  ${{ secrets.BVITY_SLACK_WEBHOOK }}
          
          curl -s -d "payload={ \"username\":\"RPPrefresh Job\", \"attachments\":[{\"color\":\"#E01E5A\" , \"text\": \"Test $(echo ${{ toJson(github.event_name) }}) Ignore <${URL}|linking>\"}]}" ${{ secrets.BVITY_SLACK_WEBHOOK }}
