name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is yobo 
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octoc
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
        pwd
        sudo service httpd status
        echo GITHUB_REF=${GITHUB_REF}
        echo EXTRACT_GITHUB_REF=${GITHUB_REF##*/}
        echo EXTRACT_GITHUB_REF_HEADS=$(echo ${GITHUB_REF#refs/heads/})
