name: pr

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
    - name: Checkout code
      uses: actions/checkout@master
    
    - name: Show Popularity
      id: popular
      run: |
        set -exv
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        GIT_TAGS=$(git tag -l --sort=committerdate)  
        TAGS=($GIT_TAGS)
        echo "${{ toJson(github.event_path) }}"
        export COMMIT=rc-${TAGS[0]}-$(jq --raw-output .head_commit.id "${{ github.event_path }}" | cut -c1-7)
        export COMMIT_HASHH=$(jq --raw-output .sha "${{ github.event_path }}" | cut -c1-7)
        echo "******************************"
        echo $COMMIT_HASHH
        echo "********"
        echo $COMMIT
        echo "******************************"
        echo "The github context is:"
        echo "${{ toJson(github) }}"
        echo ""
        echo "The job context is:"
        echo "${{ toJson(job) }}"
        echo ""
        echo "The steps context is:"
        echo "${{ toJson(steps) }}"
        echo ""
        echo "The runner context is:"
        echo "${{ toJson(runner) }}"
        echo ""
        echo "The strategy context is:"
        echo "${{ toJson(strategy) }}"
        echo ""
        echo "The matrix context is:"
        echo "${{ toJson(matrix) }}"

  exitis:
    if: "!github.event.release.prerelease"
    runs-on: [ubuntu-latest]
    steps:
      - name: step1 
        run: |
          echo "chill pill"
  
