name: Release
on:
  release:
    types: 
      - published
      - edited
  repository_dispatch:
    types: 
      - rcanary
      - rtrigger

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    
    - name: pre
      if: github.event.release.name != 'rcanary' && !github.event.release.prerelease
      run: |
        echo "not canary atall"
    - name: testing this
      run: |
        set -exv
        echo ${{ github.event_type }}
        echo ${{ github.event.release.name }}
        echo ${{ github.event.release.body }}
        if [ ${{ github.event.release.name }} == 'canary' ]; then
        ##if [[ "${{ github.event.release.name }}" =~ *"anary"* ]]; then
          echo "this is canry"
         else
          echo "this is not a canary"
        fi
        echo "Release github event payload"
        echo "${{ toJson(github) }}" 
        
    - uses: actions/checkout@v2    
    - name: second
      run: |
        set -exv
        cd ${{ github.workspace }}
        ls
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        PREVIOUS_TAG=$(GIT_TAGS=$(git tag -l --sort=-committerdate | cut -f2 -d"-") && TAGS=($GIT_TAGS) && echo ${TAGS[1]} | xargs)
        echo $PREVIOUS_TAG
  two:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event.action != 'rtrigger'
      - name: two steps
        if: github.event.action != 'rtrigger'
        run: |
          echo ${{ github.event.client_payload }}
          
      - name: failure
        if: failure()
        run: |
          echo "failure"
#       - name: success
#         if: success()
#         run: |
#           echo "success"
          
  two-mid:
    needs: [two]
    runs-on: ubuntu-latest
    steps:
      - name: run it
        run: |
          echo "mid two"
          
  three:
    runs-on: ubuntu-latest
    if: github.event.action != 'rcanary' || !github.event.release.prerelease
    steps:
      - name: three steps
        run: |
          echo ${{ github.event.client_payload }}
          echo ${{ github.event.client_payload.version }}
          echo "${{ toJson(github) }}" 
          
  fourth:
    runs-on: ubuntu-latest
    if: github.event.action != 'rcanary' && !github.event.release.prerelease
    steps:
      - name: fourth steps
        run: |
          echo ${{ github.event.client_payload }}
          echo ${{ github.event.client_payload.version }}
          echo "${{ toJson(github) }}" 
