name: Release
on:
  release:
    types: 
      - published
      - edited

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
    - name: testing this
      run: |
        set -exv
        echo ${{ github.event.release.name }}
        echo ${{ github.event.release.body }}
        ###if [ ${{ github.event.release.name }} == *"anary"* ]; then
        if [[ "${{ github.event.release.name }}" =~ *"anary"* ]]; then
          echo "this is canry"
         else
          echo "this is not a canary"
        fi
        echo "Release github event payload"
        echo "${{ toJson(github) }}" 
        
    - uses: actions/checkout@v2    
    - name: second
      run: |
        set -exv
        cd ${{ github.workspace }}
        ls
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        PREVIOUS_TAG=$(GIT_TAGS=$(git tag -l --sort=-committerdate | cut -f2 -d"-") && TAGS=($GIT_TAGS) && echo ${TAGS[1]} | xargs)
        echo $PREVIOUS_TAG
