name: Daily Backup Job
on:
#   schedule: 
#     - cron: '*/5 * * * *'
  repository_dispatch:
    types: schedule

jobs:
  run-this:
    runs-on: ubuntu-latest
    steps:
    - name: Get text value from payload
      run: |
          echo "The github context is:"
          echo "${{ toJson(github) }}"
          echo "Action url is ${{ env.ACTION_URL }}"
          echo "Event Payload"
          echo "${{ github.event.client_payload.text }} "
          pwd
          ls
          
  checker:
    if: github.event_name == 'schedule' || github.event.client_payload.action == 'checker'
    runs-on: [ubuntu-latest]
    steps:
    - name: checker
      run: |
        echo "checker"
        
  check:
    if: github.event_name == 'schedule'
    runs-on: [ubuntu-latest]
    steps:
    - name: check
      run: |
        echo "check"  
