name: Tags Trigger Workflow Now

on: 
  push: 
    tags:
      - "*lyme*"
      
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy to all env? Options: all, staging, prod'
          required: true
          default: "all"

jobs:
  opt:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - name: skip-workflow
        run: echo "hi"
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch }}
