name: Tags Trigger Workflow Now

on: 
  push: 
    tags:
      - "*lyme*"
      - "*time*"
      - "*june*"
      
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy to all env? Options: all, staging, prod'
          required: true
          default: "all"

jobs:
  opt:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - run: echo "tag v${{ github.ref_name }} got tagged"
      - name: skip-workflow
        run: echo "hi"
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: time all
        run: echo "hi time all"
        if: github.ref_name == '*time*'
      - name: time
        run: echo "time"
        if: github.ref_name == '*time'
      - name: june
        run: echo "hi jun"
        if: github.ref_name == '*june'
