name: Tags Trigger Workflow Now

on: 
  release:
    types:
      - published
      
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy to all env? Options: all, staging, prod'
          required: true
          default: "all"
        client:
          description: 'select client.'
          required: true
          default: 'all' 
          type: choice
          options:
          - all
          - john
          - smith
          - aim

env:
  CLIENTS: "john smith aim"
  # VERSION: "latest"
  ACTION_URL: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"

jobs:
  first-job:
    runs-on: ubuntu-latest  
    steps:
    - id: identify
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="male"
        export GIT_PR_SHA_SHORT="female"
        export TAGS=${{ github.ref_name }}

        echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
        echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"
        echo "::set-output name=tags::${TAGS}"
    outputs:
      git_pr_sha: ${{ steps.identify.outputs.git_pr_sha }}
      git_pr_sha_short: ${{ steps.identify.outputs.git_pr_sha_short }}
      tags: ${{ steps.identify.outputs.tags }}

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ needs.first-job.outputs.git_pr_sha }}"
        echo "${{ needs.first-job.outputs.git_pr_sha_short }}"
        echo "${{ needs.first-job.outputs.tags }}"
  
  build:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
    # - run: echo "${{ toJson(github) }}"
    - id: tags
      run: |
        # set -exv
        if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
          echo "manual flow"
          clients="${{ env.CLIENTS }}"
          for client in $clients; do
            if [ ${{ github.event.inputs.client }} == *"$client"* ]; then
              echo "VERSION=${{ github.event.inputs.client }}-latest" >> $GITHUB_ENV
              # echo "$VERSION set"
            fi
          done
        fi

        if [ ${{ github.event_name }} == 'release' ]; then
          echo "release flow"
          for client in ${{ env.CLIENTS }}; do
            if [[ ${{ github.ref_name }} == *"$client"* ]]; then
              echo "VERSION=$client-latest" >> $GITHUB_ENV
              # echo "$VERSION set"
            fi
          done
        fi

        echo "$VERSION set"

        export TAGS=$VERSION
        echo "$TAGS is the tag"

        echo "::set-output name=tags::${TAGS}"

        # if [ ${{ github.event.inputs.client }} == 'john' ]
        #   echo "VERSION=${{ github.event.inputs.client }}-latest" >> $GITHUB_ENV

        # if ${{ !endsWith(github.ref, 'john') }} && ${{ !endsWith(github.ref, 'smith') }} && ${{ !endsWith(github.ref, 'aim') }}; then
        #   echo "deploying $version to all environment"
        # fi
        echo "${{ needs.first-job.outputs.tags }}"
    - name: Build
      run: echo "we are building $VERSION"
    outputs:
      tags: ${{ steps.tags.outputs.tags }}
  #     - uses: actions/checkout@v2

  #     - name: Build and push
  #       if: github.event_name == 'release'
  #       run: docker build -t react-app:${{ github.ref_name }} .

  #     - name: Build and Push Container
  #       if: github.event_name == 'workflow_dispatch'
  #       run: |
  #         if [ ${{ github.event.inputs.client }} == 'all' ]; then
  #           clients="${{ env.CLIENTS }}"
  #           for client in ${clients//,/ }; do
  #             docker build -t react-app:$client .
  #           done
  #         else            
  #           docker build -t react-app:${{ github.event.inputs.client }} .
  #         fi
  
  john-all:
    name: John
    runs-on: ubuntu-latest
    if:  ((${{ github.event.inputs.client }}  == 'john') || (${{ github.event.inputs.client }}  == 'all'))
    needs: build
    steps:
      - name: Run
        run: |
          echo "hi john"
          echo "${{ needs.build.outputs.tags }}"
          echo "we are building ${{ needs.build.outputs.tags }}"


  smith-all:
    name: smith
    runs-on: ubuntu-latest
    if: (${{ github.event.inputs.client }}  == 'smith') || (${{ github.event.inputs.client }}  == 'all')
    needs: build
    steps:
      - name: Run
        run: |
          echo "hi smith"
          echo "${{ needs.build.outputs.tags }}"
          echo "we are building ${{ needs.build.outputs.tags }}"

  checker-all:
    name: check all
    runs-on: ubuntu-latest
    # if: "${{ startsWith(github.ref, 'v[1-9].[1-9].[1-9]')}}"
    needs: build
    steps:
      - name: Run
        run: |
          echo "hi smith"
          echo "${{ needs.build.outputs.tags }}"
          echo "we are building ${{ needs.build.outputs.tags }}"
  # john2:
  #   name: John2
  #   runs-on: ubuntu-latest
  #   if: endsWith(github.ref, 'john') && 
  #   # needs:
  #   #   - build
  #   steps:
  #     - name: Run
  #       run: |
  #         echo "hi john2"

  dp:
    runs-on: ubuntu-latest
    if: github.ref == 'v[12].[0-9]+.[0-9]'
    # needs:
    #   - build
    steps:
      - name: Run
        run: |
          # set -exv
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            if [ ${{ github.event.inputs.client }} == 'all' ]; then
              ## We obtain the list of client from the env we specified in env
              clients="${{ env.CLIENTS }}"
              for client in ${clients//,/ }; do
                echo "NAMESPACE=${{ github.event.inputs.client }}" >> $GITHUB_ENV
                echo "$NAMESPACE"
              done
            else        
              echo "run it $NAMESPACE"
            fi
          fi

          if [ ${{ github.event_name }} == 'release' ]; then
            clients="${{ env.CLIENTS }}"
            version="${{ github.ref_name }}"
            if ${{ !endsWith(github.ref, 'john') }} && ${{ !endsWith(github.ref, 'smith') }} && ${{ !endsWith(github.ref, 'aim') }}; then
              echo "deploying $version to all environment"
            fi
            for client in $clients; do
              if [[ ${{ github.ref }} == *"$client"* ]]; then
                echo "deploying $version to $client"
              fi
            done
          fi
  opt:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - run: echo "tag v${{ github.ref_name }} got tagged"

      - name: skip-workflow
        run: echo "hi"

      - uses: actions/checkout@v2
        if: github.event_name == 'push'

      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: smith
        if: endsWith(github.ref, 'smith')
        run: echo "hi smith"


      - name: john
        if: endsWith(github.ref, 'john')
        run: echo "hi john"


      # - name: john
      #   if: ${{ github.event.release.name }} == "john"
      #   run: echo "hi john"

      # - name: john test
      #   if: endsWith(github.ref, 'john')
      #   run: echo "hi john test"

      # - name: 1st not
      #   if: ${{ !endsWith(github.ref, 'john') }}
      #   run: echo "no john"
      
      # - name: 2nd not
      #   if: ${{ !contains(fromJson('["john", "smith"]'), github.ref) }}
      #   run: echo "no john not smith"

      # - name: 2nd not
      #   if: ${{ !contains(["john", "smith"], github.ref) }}
      #   run: echo "no john not smith"

      # # - name: time all john 3
      # #   run: echo "hi time all"
      # #   if: github.ref_name == "*john"

      # - name: time all john 4
      #   run: echo "hi time all"
      #   if: github.ref_name == '*john'

      # - name: time
      #   run: echo "smith"
      #   if: github.ref_name == '*smith'

      # - name: june
      #   run: echo "hi aim"
      #   if: github.ref_name == '*aim'
