name: Tags Trigger Workflow Now

on: 
  release:
    types:
      - published
      
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy to all env? Options: all, staging, prod'
          required: true
          default: "all"
        client:
          description: 'select client.'
          required: true
          default: 'all' 
          type: choice
          options:
          - all
          - john
          - smith
          - aim

env:
  CLIENTS: "john smith aim"
  ACTION_URL: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   #if: github.event_name == 'workflow_dispatch'
  #   steps:
  #     - run: echo "${{ toJson(github) }}"
  #     - uses: actions/checkout@v2

  #     - name: Build and push
  #       if: github.event_name == 'release'
  #       run: docker build -t react-app:${{ github.ref_name }} .

  #     - name: Build and Push Container
  #       if: github.event_name == 'workflow_dispatch'
  #       run: |
  #         if [ ${{ github.event.inputs.client }} == 'all' ]; then
  #           clients="${{ env.CLIENTS }}"
  #           for client in ${clients//,/ }; do
  #             docker build -t react-app:$client .
  #           done
  #         else            
  #           docker build -t react-app:${{ github.event.inputs.client }} .
  #         fi
  
  dp:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    # needs:
    #   - build
    steps:
      - name: Run
        run: |
          set -exv
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            if [ ${{ github.event.inputs.client }} == 'all' ]; then
              ## We obtain the list of client from the env we specified in env
              clients="${{ env.CLIENTS }}"
              for client in ${clients//,/ }; do
                echo "NAMESPACE=${{ github.event.inputs.client }}" >> $GITHUB_ENV
                echo "$NAMESPACE"
              done
            else        
              echo "run it $NAMESPACE"
            fi
          fi

          if [ ${{ github.event_name }} == 'release' ]; then
            clients="${{ env.CLIENTS }}"
            version="${{ github.ref_name }}"
            for cl in $clients; do
              echo "checking $cl"
              export cl=$cl
              # if [[ $version != *"john"* ]] && [[ $version != *"smith"* ]] && [[ $version != *"aim"* ]]; then
              # if [[ $version != *"john"* ]] && [[ $version != *"smith"* ]] && [[ $version != *"aim"* ]]; then
              if ${{ !endsWith(github.ref, 'john') }} && ${{ !endsWith(github.ref, 'smith') }} && ${{ !endsWith(github.ref, 'aim') }}; then
                echo "deploy $cl"
              fi
                # if [[ $version == *"$cl"* ]]; then
              echo "check if ${{ github.ref }} ends with $cl"
              # if [[ ${{ github.ref }} == *"$cl"* ]]; then
              if endsWith(github.ref, ${{ env.cl }}) ; then
                echo "deploying $version to $cl"
              fi
            done
          fi
  opt:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - run: echo "tag v${{ github.ref_name }} got tagged"

      - name: skip-workflow
        run: echo "hi"

      - uses: actions/checkout@v2
        if: github.event_name == 'push'

      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: smith
        if: endsWith(github.ref, 'smith')
        run: echo "hi smith"


      - name: john
        if: endsWith(github.ref, 'john')
        run: echo "hi john"


      # - name: john
      #   if: ${{ github.event.release.name }} == "john"
      #   run: echo "hi john"

      # - name: john test
      #   if: endsWith(github.ref, 'john')
      #   run: echo "hi john test"

      # - name: 1st not
      #   if: ${{ !endsWith(github.ref, 'john') }}
      #   run: echo "no john"
      
      # - name: 2nd not
      #   if: ${{ !contains(fromJson('["john", "smith"]'), github.ref) }}
      #   run: echo "no john not smith"

      # - name: 2nd not
      #   if: ${{ !contains(["john", "smith"], github.ref) }}
      #   run: echo "no john not smith"

      # # - name: time all john 3
      # #   run: echo "hi time all"
      # #   if: github.ref_name == "*john"

      # - name: time all john 4
      #   run: echo "hi time all"
      #   if: github.ref_name == '*john'

      # - name: time
      #   run: echo "smith"
      #   if: github.ref_name == '*smith'

      # - name: june
      #   run: echo "hi aim"
      #   if: github.ref_name == '*aim'
