name: Tags Trigger Workflow Now

on: 
  release:
    - published
      
  workflow_dispatch:
      inputs:
        deploy:
          description: 'Deploy to all env? Options: all, staging, prod'
          required: true
          default: "all"
        client:
          description: 'select client.'
          required: true
          default: 'all' 
          type: choice
          options:
          - all
          - john
          - smith
          - aim

env:
  CLIENTS: "john,smith,aim"
  ACTION_URL: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - uses: actions/checkout@v2

      - name: Build and push
        if: github.event_name == 'release'
        run: docker build -t react-app:${{ github.ref_name }} .

      - name: Build and Push Container
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ ${{ github.event.inputs.client }} == 'all' ]; then
            clients="${{ env.CLIENTS }}"
            for client in ${clients//,/ }; do
              docker build -t react-app:$client .
            done
          else            
            docker build -t react-app:${{ github.event.inputs.client }} .
          fi
  dp:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    needs:
      - build
    steps:
      - name: Run
        run: |
          set -exv
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            if [ ${{ github.event.inputs.client }} == 'all' ]; then
              ## We obtain the list of client from the env we specified in env
              clients="${{ env.CLIENTS }}"
              for client in ${clients//,/ }; do
                echo "NAMESPACE=${{ github.event.inputs.client }}" >> $GITHUB_ENV
                echo "$NAMESPACE"
              done
            else        
              echo "run it $NAMESPACE"
            fi
          fi

          if [ ${{ github.event_name }} == 'release' ]; then
            clients="${{ env.CLIENTS }}"
            version="${{ github.ref_name }}"
            for client in $clients; do
              if [[ $version != *"john"* ]] && [[ $version != *"smith"* ]] && [[ $version != *"aim"* ]]; then
                echo "deploy $client"
              else
                if [[ $version == *"$client"* ]]; then
                  echo "deploying $version to $client"
                else
                  echo "not deploying to $client."
                fi
              fi
            done
          fi
  opt:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - run: echo "${{ toJson(github) }}"
      - run: echo "tag v${{ github.ref_name }} got tagged"
      - name: skip-workflow
        run: echo "hi"
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
      - uses: actions/checkout@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: time all
        run: echo "hi time all"
        if: github.ref_name == '*time*'
      - name: time
        run: echo "time"
        if: github.ref_name == '*time'
      - name: june
        run: echo "hi jun"
        if: github.ref_name == '*june'
