name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to all env?'
        required: false
        default: 'all'
      staging:
        description: 'Deploy to staging? Option yes/no'
        required: false
      prod:
        description: 'Profile'
        required: false
        default: 'aim'
      profile:
        description: 'Prvphyle'
        required: false
        default: 'mytrik'
      user:
        description: 'wlpy'
        required: false
        default: 'wl'
  repository_dispatch:
    types: dispatch
  push:
    branches: master

env:
  ACTION_URL: "https://github.com/${{ toJson(github.repository) }}/commit/${{ toJson(github.sha) }}/checks"
jobs:
  run-this:
    runs-on: ubuntu-latest
    steps:
    - name: Get Workflow payload
      run: |
        echo "${{ toJson(github) }}"
    - run: echo "1"
      if: github.event_name
    - run: echo "2"
      if: "!github.event_name"
    - run: echo "3"
      if: github.event_name == ('release'|'repository_dispatch')
    - run: echo "4"
      if: github.event_name == ('release'|'repository_dispatch'|'workflow_dispatch')
    - run: echo "5"
      if: github.event_name == ('repository_dispatch'|'workflow_dispatch')
    - run: echo "6"
      if:  github.event_name && github.event_name == ('release'|'repository_dispatch'|'workflow_dispatch')
